language: javascript

install:
  - npm cache && npm install -g n --force
  - which n
  - n 8.9.0
  -

cache:
  directories:
    - ./node_modules

matrix:
  include:
    - env:
      - TASK=build
      script: 
        - npm install

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
