language: javascript

install:
  - wget https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-x64.tar.xz && xz -d node-v8.11.3-linux-x64.tar.xz && tar -xvf node-v8.11.3-linux-x64.tar
  - echo “\n” >> ${TRAVIS_HOME}/.bashrc
  - echo "export PATH=/${TRAVIS_HOME}/node-v8.11.3-linux-x64/bin/node:$PATH" >> ${TRAVIS_HOME}/.bashrc
  - echo “\n” >> ${TRAVIS_HOME}/.bashrc
  - echo "export PATH=/${TRAVIS_HOME}/node-v8.11.3-linux-x64/bin/npm:$PATH" >> ${TRAVIS_HOME}/.bashrc
  - source ${TRAVIS_HOME}/.bashrc
  -

cache:
  directories:
    - ./node_modules

matrix:
  include:
    - env:
      - TASK=build
      script: ./node-v8.11.3-linux-x64/bin/npm install

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
