language: javascript

before_install:
  - sudo chmod 0777 /usr/local/

install:
  - npm install -g n --force
  - PATH=$PATH:/home/travis/.nvm/versions/node/v4.1.2/bin/
  - n 8.9.0
  - PATH=$PATH:/home/travis/.nvm/versions/node/v8.9.0/bin/
  - n 8.9.0
  -

cache:
  directories:
    - ./node_modules

matrix:
  include:
    - env:
      - TASK=build
      script: 
        - npm install

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
